### ISSUE TITLE
"Purchase Vouchers" Button fehlt.

### ISSUE THREAD

**Issue by jockschulz** [elmariachi111/welshare_kyc#3]
"Purchase Vouchers" Button fehlt. Link zu: https://juicebox.money/@welshare
![image_2024-09-30_13-07-32](https://github.com/user-attachments/assets/5a08ec37-cd4c-47d3-84aa-38a1fee58e87)

**Comment by elmariachi111** [comment]
reactivated buttons with old code base https://github.com/elmariachi111/welshare_kyc/commit/b78cfae68ac1e0bbd9bc9c2bb15d0f3cc0414cdf#diff-21f0cf16ced159fa60114473ebf48ff3184b6dc2fd7b7d16e28033de0744d485L81
