### ISSUE TITLE
Social preview

### ISSUE THREAD

**Issue by jockschulz** [elmariachi111/welshare_kyc#5]
![image_2024-09-30_13-09-16 3](https://github.com/user-attachments/assets/fc945a28-7144-4e59-8b8f-63bbf173ebee)
Können wir Social preview auch aktualisieren zu Phase 2?

**Comment by elmariachi111** [comment]
updated the images, twitter still caches the old ones :( Elon also disabled all debugging options here so it's really hard to figure out how to fix that...
